### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by bbrietzke** [mwells/ocaml-cgi#5]
Was trying to build the package, when I get the following:

```
make -C src
echo compatability.ml headers.ml http_header.ml http_method.ml http_status.ml netstring.ml request.ml response.ml server.ml | perl -pe 's/ /\n/g'  | perl -pe 's/^./\U$&/g' | sed -e "s/\.ml//g" | grep -v myocamlbuild | sort > scgi.mlpack
ocamlbuild -tag debug scgi.cma scgi.cmxa
+ /usr/local/bin/ocamlopt.opt unix.cmxa -I /usr/local/lib/ocaml/ocamlbuild /usr/local/lib/ocaml/ocamlbuild/ocamlbuildlib.cmxa myocamlbuild.ml /usr/local/lib/ocaml/ocamlbuild/ocamlbuild.cmx -o myocamlbuild
File "myocamlbuild.ml", line 12, characters 4-76:
Error: This expression has type Lexing.lexbuf
       but an expression was expected of type
         Ocamlbuild_pack.Loc.source = string
Command exited with code 2.
Compilation unsuccessful after building 1 target (0 cached) in 00:00:00.
make[1]: *** [all] Error 10
make: *** [src] Error 2
```

Was wondering if you could provide some insight as to what is generating the error.

**Comment by crazykt** [comment]
Hi,

I am facing the same problem. Can you tell me how you were able to fix this?

**Comment by bbrietzke** [comment]
i have been able to fix this.

**Comment by crazykt** [comment]
Can you tell me how you were able to fix this?

**Comment by rjnn** [comment]
@crazykt : It's a problem with ocamlbuild version 4.02. This repository builds fine on ocaml version 4.01, but not 4.02, because something has changed in the format of how ocamlbuilds are specified. Maybe one day I'll understand ocamlbuild and be able to help fix it.

 I just wasted an hour here since @bbrietzke just pulled a DenverCoder9... Hope this helps anyone in the future! http://xkcd.com/979/

**Comment by crazykt** [comment]
@arjunravinarayan : Thanks, I was able to build it with ocamlbuild version 4.01.
